// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace HashtilERP.Data
{
    public partial class HashtilERPContext : DbContext
    {
        public HashtilERPContext()
        {
        }

        public HashtilERPContext(DbContextOptions<HashtilERPContext> options)
            : base(options)
        {
        }

        public virtual DbSet<KPassport> KPassport { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("db_datareader")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP850_CI_AS");

            modelBuilder.Entity<KPassport>(entity =>
            {
                entity.ToTable("K_Passport");

                entity.Property(e => e.KPassportId)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("K_PassportId");
                    

                entity.Property(e => e.Gamlon)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.Hamama)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.PassportAvg).HasColumnName("PassportAVG");

                entity.Property(e => e.PassportStatus)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.SowDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<Passport>(entity =>
            {
                entity.HasKey(e => e.DocEntry)
                    .HasName("KPASSPORT_PR");

                entity.ToTable("@PASSPORT", "dbo");

                entity.HasIndex(e => e.DocNum, "IX_@PASSPORT_DocNum");

                entity.Property(e => e.DocEntry).ValueGeneratedNever();

                entity.Property(e => e.Canceled)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.CreateDate).HasColumnType("datetime");

                entity.Property(e => e.Creator).HasMaxLength(8);

                entity.Property(e => e.DataSource)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Handwrtten)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Object).HasMaxLength(20);

                entity.Property(e => e.Remark).HasColumnType("ntext");

                entity.Property(e => e.RequestStatus)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Status)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Transfered)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.UBatchCheck)
                    .HasColumnType("ntext")
                    .HasColumnName("U_BatchCheck");

                entity.Property(e => e.UBatchNum)
                    .HasMaxLength(20)
                    .HasColumnName("U_BatchNum");

                entity.Property(e => e.UBatchavg)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_batchavg");

                entity.Property(e => e.UBplntPct)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_BplntPct");

                entity.Property(e => e.UBplntTr)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_BPlntTr");

                entity.Property(e => e.UDateCrea)
                    .HasColumnType("datetime")
                    .HasColumnName("U_DateCrea");

                entity.Property(e => e.UDateEnd)
                    .HasColumnType("datetime")
                    .HasColumnName("U_DateEnd");

                entity.Property(e => e.UDateMxGr)
                    .HasColumnType("datetime")
                    .HasColumnName("U_DateMxGr");

                entity.Property(e => e.UDateSow)
                    .HasColumnType("datetime")
                    .HasColumnName("U_DateSow");

                entity.Property(e => e.UGamlon)
                    .HasMaxLength(20)
                    .HasColumnName("U_Gamlon");

                entity.Property(e => e.UGermPrct)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_GermPrct");

                entity.Property(e => e.UGrnHos)
                    .HasMaxLength(20)
                    .HasColumnName("U_GrnHos");

                entity.Property(e => e.UGroomTemp)
                    .HasMaxLength(10)
                    .HasColumnName("U_GroomTemp");

                entity.Property(e => e.UItemAvg)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_ItemAvg");

                entity.Property(e => e.UItemCode)
                    .HasMaxLength(20)
                    .HasColumnName("U_ItemCode");

                entity.Property(e => e.UItemDesc)
                    .HasMaxLength(100)
                    .HasColumnName("U_ItemDesc");

                entity.Property(e => e.ULossPct)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_LossPct");

                entity.Property(e => e.UMachine)
                    .HasMaxLength(20)
                    .HasColumnName("U_Machine");

                entity.Property(e => e.UNights)
                    .HasMaxLength(10)
                    .HasColumnName("U_Nights");

                entity.Property(e => e.UNotGrow)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_NotGrow");

                entity.Property(e => e.UNote1)
                    .HasMaxLength(30)
                    .HasColumnName("U_Note1");

                entity.Property(e => e.UNote2)
                    .HasMaxLength(30)
                    .HasColumnName("U_Note2");

                entity.Property(e => e.UNote3)
                    .HasMaxLength(30)
                    .HasColumnName("U_Note3");

                entity.Property(e => e.UNote4)
                    .HasMaxLength(30)
                    .HasColumnName("U_Note4");

                entity.Property(e => e.UNotes)
                    .HasColumnType("ntext")
                    .HasColumnName("U_Notes");

                entity.Property(e => e.UPassNum)
                    .HasMaxLength(20)
                    .HasColumnName("U_PassNum");

                entity.Property(e => e.UPassSirs)
                    .HasMaxLength(50)
                    .HasColumnName("U_PassSirs");

                entity.Property(e => e.UPassStat)
                    .HasMaxLength(20)
                    .HasColumnName("U_PassStat");

                entity.Property(e => e.UPeat)
                    .HasMaxLength(10)
                    .HasColumnName("U_Peat");

                entity.Property(e => e.UPostSort)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_PostSort");

                entity.Property(e => e.UPreSort)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_PreSort");

                entity.Property(e => e.UQuanElim)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_QuanElim");

                entity.Property(e => e.UQuanInvt)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_QuanInvt");

                entity.Property(e => e.UQuanOrdI)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_QuanOrdI");

                entity.Property(e => e.UQuanOrdP)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_QuanOrdP");

                entity.Property(e => e.UQuanProd)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_QuanProd");

                entity.Property(e => e.UQuanSpar)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_QuanSpar");

                entity.Property(e => e.URecTray)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_RecTray");

                entity.Property(e => e.USeedComp)
                    .HasMaxLength(100)
                    .HasColumnName("U_SeedComp");

                entity.Property(e => e.USowTemp)
                    .HasMaxLength(10)
                    .HasColumnName("U_SowTemp");

                entity.Property(e => e.USowrName)
                    .HasMaxLength(50)
                    .HasColumnName("U_sowrName");

                entity.Property(e => e.USplntPct)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_SPlntPct");

                entity.Property(e => e.USplntTr)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_SPlntTr");

                entity.Property(e => e.UTimeSow).HasColumnName("U_TimeSow");

                entity.Property(e => e.UTrLoss)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_TrLoss");

                entity.Property(e => e.UTrayAvrg)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_TrayAvrg");

                entity.Property(e => e.UTrayGre)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_TrayGre");

                entity.Property(e => e.UTraySow)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_TraySow");

                entity.Property(e => e.UZanZl)
                    .HasMaxLength(20)
                    .HasColumnName("U_Zan_ZL");

                entity.Property(e => e.UZraCoef)
                    .HasColumnType("numeric(19, 6)")
                    .HasColumnName("U_ZraCoef");

                entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}