// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.Data
{
    public partial class KPassport
    {
        public int KPassportId { get; set; }
        public int PassportNum { get; set; }
        public string GrowingRoom { get; set; }
        public DateTime? SowDate { get; set; } = DateTime.Today;
        public int PassportAge 
        {
            get { return Convert.ToInt32(((TimeSpan)(DateTime.Now - SowDate)).Days); }
        }
        public string Hamama { get; set; }
        public string Gamlon { get; set; }
        public int? MagashAmount { get; set; }
        public int? OriginalMagashAmount { get; set; }
        public int? PlantsAmount { get; set; }
        public bool? IsNeedToBeAudit { get; set; }
        public bool? IsNeedToBeChecked { get; set; }
        public string PassportStatus { get; set; }
        public int? PassportAvg { get; set; }
       
    }
}