// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.Data
{
    public partial class KPassportInsertAudit
    {
        public string UserName { get; set; }
        public DateTime? Date { get; set; }
        public int? PassportNum { get; set; }
        public int KPassportId { get; set; }
    }
}