// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace HashtilERP.Data
{
    public partial class KPassport
    {
        public int KPassportId { get; set; }
        public int? SapDocEntry { get; set; }
        public int PassportNum { get; set; }
        public string GrowingRoom { get; set; }
        public DateTime? SowDate { get; set; }
        public string Hamama { get; set; }
        public string Gamlon { get; set; }
        public int? MagashAmount { get; set; }
        public int? PlantsAmount { get; set; }
        public bool? IsNeedToBeAudit { get; set; }
        public bool? IsNeedToBeChecked { get; set; }
        public string PassportStatus { get; set; }
        public int? PassportAvg { get; set; }
        public int? OriginalMagashAmount { get; set; }
        public string ItemCode { get; set; }

        [ForeignKey("SapDocEntry")]
        public Passport Passport { get; set; }
        
    }
}