// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace HashtilERP.Data
{
    public partial class ORDR
    {
        [Key]
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string CardCode { get; set; }
    }
}