// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.DBTestVol1
{
    public partial class KOrderPassports
    {
        public int PassportsToOrdersId { get; set; }
        public int? JobId { get; set; }
        public int? KPassportId { get; set; }
        public int? PassportMagashAmpunt { get; set; }
    }
}