// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace HashtilERP.DBTestVol1
{
    public partial class KOrderPassports
    {
        public int PassportsToOrdersId { get; set; }
        public int? JobId { get; set; }
        public int? K_PassportId { get; set; }
        public int? PassportMagashAmpunt { get; set; }
        public string UserName { get; set; }
        public int? SelectedAVG { get; set; }
        public int? K_PassportNum { get; set; }
        public int KpassportHamama { get; set; }
        public int KpassportGamlon { get; set; }

        [ForeignKey("K_PassportId")]
        public KPassport K_Passport { get; set; }
    }
}