// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.DBTestVol1
{
    public partial class UpdateKPassportAudit
    {
        public int UpdateKPassportAuditId { get; set; }
        public int KPassportId { get; set; }
        public string UserName { get; set; }
        public DateTime? Date { get; set; }
        public string HamBefore { get; set; }
        public string HamAfter { get; set; }
        public string GamBefore { get; set; }
        public string GamAfter { get; set; }
        public string MagBefore { get; set; }
        public string MagAfter { get; set; }
        public string Avgbefore { get; set; }
        public string Avgafter { get; set; }
        public string StatBefore { get; set; }
        public string StatAfter { get; set; }
    }
}