// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.TestContextApi
{
    public partial class DriversToOrder
    {
        public int DriversToOrderId { get; set; }
        public int? JobId { get; set; }
        public string DriverId { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string ScreenName { get; set; }
    }
}