// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.TestContextApi
{
    public partial class KOrderForBartender
    {
        public int KorderForBarTenderId { get; set; }
        public int? KorderId { get; set; }
        public int? Passport1 { get; set; }
        public int? Hamama1 { get; set; }
        public int? Gamlon1 { get; set; }
        public int? Magash1 { get; set; }
        public int? Passport2 { get; set; }
        public int? Hamama2 { get; set; }
        public int? Gamlon2 { get; set; }
        public int? Magash2 { get; set; }
        public int? Passport3 { get; set; }
        public int? Hamama3 { get; set; }
        public int? Gamlon3 { get; set; }
        public int? Magash3 { get; set; }
        public int? Passport4 { get; set; }
        public int? Hamama4 { get; set; }
        public int? Gamlon4 { get; set; }
        public int? Magash4 { get; set; }
        public int? Passport5 { get; set; }
        public int? Hamama5 { get; set; }
        public int? Gamlon5 { get; set; }
        public int? Magash5 { get; set; }
        public int? Passport6 { get; set; }
        public int? Hamama6 { get; set; }
        public int? Gamlon6 { get; set; }
        public int? Magash6 { get; set; }
    }
}