// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.TestContextApi
{
    public partial class KOrderRemark
    {
        public int KOrderRemarkId { get; set; }
        public int? JobId { get; set; }
        public string UserName { get; set; }
        public DateTime? KOrderRemarkStamp { get; set; }
        public string Remark { get; set; }
    }
}