// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.TestContextApi
{
    public partial class KOrderPassports
    {
        public int PassportsToOrdersId { get; set; }
        public int? JobId { get; set; }
        public int? KPassportId { get; set; }
        public int? PassportMagashAmpunt { get; set; }
        public string UserName { get; set; }
        public int? SelectedAvg { get; set; }
        public int? KPassportNum { get; set; }
        public int? KpassportHamama { get; set; }
        public int? KpassportGamlon { get; set; }
    }
}