// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.TestContextApi
{
    public partial class KPassportExcelInsert
    {
        public int KPassportExcelId { get; set; }
        public int? Hamama { get; set; }
        public int? Gamlon { get; set; }
        public int? Passport { get; set; }
        public int? Magash { get; set; }
        public int? Avarage { get; set; }
    }
}