// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.TestContextApi
{
    public partial class KPassportAuditTblVer2
    {
        public int Id { get; set; }
        public int? KPassportId { get; set; }
        public string UserName { get; set; }
        public DateTime? Date { get; set; }
        public string AuditString { get; set; }
    }
}