// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HashtilERP.TestContextApi
{
    public partial class PassportAuditForm
    {
        public long PassportAuditFormId { get; set; }
        public int KPassportId { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UserName { get; set; }
        public string AuditStatus { get; set; }
        public string Remark { get; set; }
    }
}